export const enums = {
  largestWeb: "Most Visited Indian E-commerce Website",
  minimumPrice: "Shop at minimum prices",
  newArrival: "New Arrivals Only",
  allProducts: "All Products",
  copyRight:
    "Copyright 2024 All rights reserved | This template is made with love by Shoppe.com",
  showResults: "Showing Results",
  sort: "Sort by",
  pleaseLogin: "Please Login To Purchase Items",
  login: "Login",
  youLogged: "You are now Logged In",
  goBack: "Go back to home page",
  buyNow: "Buy Now",
  recommended: "Recommended Products",
  createNew: "Create New ?",
  enterName: "Your Name",
  enterEmail: "Your Email",
  password: "Password",
  firstName: "First Name",
  lastName: "Last Name",
  signUp: "Please Sign Up",
  crateAccount: "Create Account",
  signedUp: "You Successfully Signed Up",
  loginPage: "Go Back To Login Page",
};
